import { BiLogoPostgresql } from "react-icons/bi";
import { BsFillBootstrapFill, BsRobot } from "react-icons/bs";
import { IconType } from "react-icons/lib";
import {
  SiCss3,
  SiExpress,
  SiFirebase,
  SiJavascript,
  SiNextdotjs,
  SiNodedotjs,
  SiReact,
  SiTailwindcss,
  SiTypescript,
  SiTensorflow,
  SiCplusplus,
  SiC,
  SiHtml5,
  SiMongodb,
  SiMysql,
  SiRedis,
  SiDocker,
  SiKubernetes,
  SiGit,
  SiGithub,
  SiLinux,
  SiVercel,
  SiNetlify,
  SiOpenai,
  SiGoogle,
  SiAnthropic,
  SiStripe,
  SiRazorpay,
  SiTurborepo,
} from "react-icons/si";

export type stacksProps = Record<
  string,
  {
    Icon: IconType;
    className: string;
  }
>;

export const FRONTEND_STACKS: stacksProps = {
  "C++": { Icon: SiCplusplus, className: "" },
  JavaScript: { Icon: SiJavascript, className: "" },
  TypeScript: { Icon: SiTypescript, className: "" },
  "React.js": { Icon: SiReact, className: "" },
  "Next.js": { Icon: SiNextdotjs, className: "" },
  Redux: { Icon: SiReact, className: "" },
  TailwindCSS: { Icon: SiTailwindcss, className: "" },
  ShadcnUI: { Icon: SiTailwindcss, className: "" },
  HTML5: { Icon: SiHtml5, className: "" },
  CSS3: { Icon: SiCss3, className: "" },
  Bootstrap: { Icon: BsFillBootstrapFill, className: "" },
};

export const BACKEND_STACKS: stacksProps = {
  "Node.js": { Icon: SiNodedotjs, className: "" },
  "Express.js": { Icon: SiExpress, className: "" },
  "ASP.NET Core": { Icon: SiC, className: "" },
  "REST APIs": { Icon: SiNodedotjs, className: "" },
  WebSockets: { Icon: SiNodedotjs, className: "" },
  JWT: { Icon: SiNodedotjs, className: "" },
  OAuth: { Icon: SiNodedotjs, className: "" },
  Clerk: { Icon: SiNodedotjs, className: "" },
  NextAuth: { Icon: SiNextdotjs, className: "" },
  "Firebase Auth": { Icon: SiFirebase, className: "" },
  MongoDB: { Icon: SiMongodb, className: "" },
  MySQL: { Icon: SiMysql, className: "" },
  PostgreSQL: { Icon: BiLogoPostgresql, className: "" },
  Redis: { Icon: SiRedis, className: "" },
  Mongoose: { Icon: SiMongodb, className: "" },
  Prisma: { Icon: SiNodedotjs, className: "" },
  "Drizzle ORM": { Icon: SiNodedotjs, className: "" },
  "Entity Framework": { Icon: SiC, className: "" },
  "Microsoft Azure": { Icon: SiGoogle, className: "" },
  Vercel: { Icon: SiVercel, className: "" },
  Netlify: { Icon: SiNetlify, className: "" },
  Git: { Icon: SiGit, className: "" },
  GitHub: { Icon: SiGithub, className: "" },
  Docker: { Icon: SiDocker, className: "" },
  Kubernetes: { Icon: SiKubernetes, className: "" },
  Linux: { Icon: SiLinux, className: "" },
  GPT: { Icon: SiOpenai, className: "" },
  Claude: { Icon: SiAnthropic, className: "" },
  Gemini: { Icon: SiGoogle, className: "" },
  "AI Agents": { Icon: BsRobot, className: "" },
  "RAG Systems": { Icon: BsRobot, className: "" },
  "OpenAI Agents SDK": { Icon: SiOpenai, className: "" },
  "MCP Server": { Icon: SiOpenai, className: "" },
  "Prompt Engineering": { Icon: BsRobot, className: "" },
  "Fine-tuning": { Icon: SiTensorflow, className: "" },
  Embeddings: { Icon: BsRobot, className: "" },
  "Vector Databases": { Icon: SiMongodb, className: "" },
  Stripe: { Icon: SiStripe, className: "" },
  Razorpay: { Icon: SiRazorpay, className: "" },
  Monorepo: { Icon: SiTurborepo, className: "" },
  Turborepo: { Icon: SiTurborepo, className: "" },
};
